"""FHE-native Mamba-3 MIMO research prototype."""

from importlib.metadata import PackageNotFoundError, version

_PACKAGE_NAME = "fhe-native-mamba3"

try:
    __version__ = version(_PACKAGE_NAME)
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

_LAZY_IMPORTS = {
    "BootstrapSchedule": ("fhe_native_mamba3.cost", "BootstrapSchedule"),
    "BootstrapExecutionBlockCost": (
        "fhe_native_mamba3.bootstrap_schedule",
        "BootstrapExecutionBlockCost",
    ),
    "BootstrapExecutionPolicy": (
        "fhe_native_mamba3.bootstrap_schedule",
        "BootstrapExecutionPolicy",
    ),
    "BootstrapExecutionSchedule": (
        "fhe_native_mamba3.bootstrap_schedule",
        "BootstrapExecutionSchedule",
    ),
    "BootstrapExecutionScheduleStep": (
        "fhe_native_mamba3.bootstrap_schedule",
        "BootstrapExecutionScheduleStep",
    ),
    "CkksConfig": ("fhe_native_mamba3.ckks", "CkksConfig"),
    "CkksTrace": ("fhe_native_mamba3.ckks", "CkksTrace"),
    "CheckpointInspection": ("fhe_native_mamba3.checkpoint", "CheckpointInspection"),
    "CheckpointTensorSpec": ("fhe_native_mamba3.checkpoint", "CheckpointTensorSpec"),
    "CheckpointClientDecodeSmoke": (
        "fhe_native_mamba3.checkpoint_decode",
        "CheckpointClientDecodeSmoke",
    ),
    "CheckpointSourceProfile": (
        "fhe_native_mamba3.checkpoint_profile",
        "CheckpointSourceProfile",
    ),
    "CheckpointSourceProfileLayer": (
        "fhe_native_mamba3.checkpoint_profile",
        "CheckpointSourceProfileLayer",
    ),
    "CheckpointRecurrenceCorrectnessGate": (
        "fhe_native_mamba3.checkpoint_correctness",
        "CheckpointRecurrenceCorrectnessGate",
    ),
    "CheckpointPreRecurrenceStageGate": (
        "fhe_native_mamba3.checkpoint_pre_recurrence",
        "CheckpointPreRecurrenceStageGate",
    ),
    "CheckpointPreRecurrenceChainGate": (
        "fhe_native_mamba3.checkpoint_pre_recurrence",
        "CheckpointPreRecurrenceChainGate",
    ),
    "PRE_RECURRENCE_STAGES": (
        "fhe_native_mamba3.checkpoint_pre_recurrence",
        "PRE_RECURRENCE_STAGES",
    ),
    "CheckpointFullLayerCiphertextGate": (
        "fhe_native_mamba3.checkpoint_correctness",
        "CheckpointFullLayerCiphertextGate",
    ),
    "CheckpointFullLayerCiphertextTrace": (
        "fhe_native_mamba3.checkpoint_correctness",
        "CheckpointFullLayerCiphertextTrace",
    ),
    "CheckpointFullLayerSweepLayer": (
        "fhe_native_mamba3.checkpoint_full_layer_sweep",
        "CheckpointFullLayerSweepLayer",
    ),
    "CheckpointFullLayerSweepResult": (
        "fhe_native_mamba3.checkpoint_full_layer_sweep",
        "CheckpointFullLayerSweepResult",
    ),
    "CheckpointVisibleProjectionSweepResult": (
        "fhe_native_mamba3.checkpoint_visible_projection_sweep",
        "CheckpointVisibleProjectionSweepResult",
    ),
    "CheckpointVisibleProjectionSweepRow": (
        "fhe_native_mamba3.checkpoint_visible_projection_sweep",
        "CheckpointVisibleProjectionSweepRow",
    ),
    "ArtifactValidationIssue": (
        "fhe_native_mamba3.artifact_validation",
        "ArtifactValidationIssue",
    ),
    "ArtifactValidationResult": (
        "fhe_native_mamba3.artifact_validation",
        "ArtifactValidationResult",
    ),
    "BackendStats": ("fhe_native_mamba3.backends.base", "BackendStats"),
    "CiphertextHandoffLayer": (
        "fhe_native_mamba3.ciphertext_handoff",
        "CiphertextHandoffLayer",
    ),
    "CiphertextHandoffResult": (
        "fhe_native_mamba3.ciphertext_handoff",
        "CiphertextHandoffResult",
    ),
    "CiphertextLayoutContract": (
        "fhe_native_mamba3.openfhe_backend",
        "CiphertextLayoutContract",
    ),
    "apply_handoff_bootstrap_schedule": (
        "fhe_native_mamba3.ciphertext_handoff",
        "apply_handoff_bootstrap_schedule",
    ),
    "apply_lora_to_linear_modules": (
        "fhe_native_mamba3.range_finetune",
        "apply_lora_to_linear_modules",
    ),
    "WeightBundleRecurrenceProblem": (
        "fhe_native_mamba3.bundle_recurrence",
        "WeightBundleRecurrenceProblem",
    ),
    "MambaCheckpointAdapterReport": (
        "fhe_native_mamba3.mamba_checkpoint",
        "MambaCheckpointAdapterReport",
    ),
    "MambaCheckpointPlan": ("fhe_native_mamba3.mamba_checkpoint", "MambaCheckpointPlan"),
    "MambaLayerPlan": ("fhe_native_mamba3.mamba_checkpoint", "MambaLayerPlan"),
    "MambaLayerReferenceResult": (
        "fhe_native_mamba3.mamba_reference",
        "MambaLayerReferenceResult",
    ),
    "MambaSourceDeltaResult": (
        "fhe_native_mamba3.mamba_reference",
        "MambaSourceDeltaResult",
    ),
    "MambaSourceLayerDiagnostics": (
        "fhe_native_mamba3.mamba_reference",
        "MambaSourceLayerDiagnostics",
    ),
    "MambaSourceVisibleHandoffTensors": (
        "fhe_native_mamba3.mamba_reference",
        "MambaSourceVisibleHandoffTensors",
    ),
    "MambaStageRange": (
        "fhe_native_mamba3.mamba_reference",
        "MambaStageRange",
    ),
    "run_mamba_source_layer": (
        "fhe_native_mamba3.mamba_reference",
        "run_mamba_source_layer",
    ),
    "LayerRangeScalePlan": (
        "fhe_native_mamba3.range_calibration",
        "LayerRangeScalePlan",
    ),
    "RangeScalePlan": (
        "fhe_native_mamba3.range_calibration",
        "RangeScalePlan",
    ),
    "LoRAConfig": ("fhe_native_mamba3.range_finetune", "LoRAConfig"),
    "LoRALinear": ("fhe_native_mamba3.range_finetune", "LoRALinear"),
    "RangeLossConfig": ("fhe_native_mamba3.range_finetune", "RangeLossConfig"),
    "RangeLossResult": ("fhe_native_mamba3.range_finetune", "RangeLossResult"),
    "RangeLossTerm": ("fhe_native_mamba3.range_finetune", "RangeLossTerm"),
    "RecurrenceTraceProfile": ("fhe_native_mamba3.profiling", "RecurrenceTraceProfile"),
    "SsdPrefixScanResult": (
        "fhe_native_mamba3.ssd_prefix_scan",
        "SsdPrefixScanResult",
    ),
    "BackendCapability": ("fhe_native_mamba3.backends.capabilities", "BackendCapability"),
    "FHEBackend": ("fhe_native_mamba3.backends.base", "FHEBackend"),
    "FheCostEstimate": ("fhe_native_mamba3.cost", "FheCostEstimate"),
    "FheMamba3Block": ("fhe_native_mamba3.model", "FheMamba3Block"),
    "FheMamba3Config": ("fhe_native_mamba3.model", "FheMamba3Config"),
    "FheMamba3ForCausalLM": ("fhe_native_mamba3.model", "FheMamba3ForCausalLM"),
    "GreedyBootstrapSchedule": (
        "fhe_native_mamba3.bootstrap_schedule",
        "GreedyBootstrapSchedule",
    ),
    "HeadPackCandidate": ("fhe_native_mamba3.head_packing", "HeadPackCandidate"),
    "HeadPackSweep": ("fhe_native_mamba3.head_packing", "HeadPackSweep"),
    "IntegratedCostEstimate": ("fhe_native_mamba3.cost", "IntegratedCostEstimate"),
    "OpenFheRecurrenceProblem": (
        "fhe_native_mamba3.openfhe_backend",
        "OpenFheRecurrenceProblem",
    ),
    "OpenFheRecurrenceResult": (
        "fhe_native_mamba3.openfhe_backend",
        "OpenFheRecurrenceResult",
    ),
    "OpenFheRecurrenceCiphertextTrace": (
        "fhe_native_mamba3.openfhe_backend",
        "OpenFheRecurrenceCiphertextTrace",
    ),
    "OpenFheRecurrenceCiphertextChainResult": (
        "fhe_native_mamba3.openfhe_backend",
        "OpenFheRecurrenceCiphertextChainResult",
    ),
    "OpenFheBootstrapConfig": ("fhe_native_mamba3.backends.openfhe", "OpenFheBootstrapConfig"),
    "OpenFheBootstrapLatencyConfig": (
        "fhe_native_mamba3.bootstrap_latency",
        "OpenFheBootstrapLatencyConfig",
    ),
    "OpenFheCkksBackend": ("fhe_native_mamba3.backends.openfhe", "OpenFheCkksBackend"),
    "OfficialMambaParityResult": (
        "fhe_native_mamba3.official_parity",
        "OfficialMambaParityResult",
    ),
    "PackingPlan": ("fhe_native_mamba3.ckks", "PackingPlan"),
    "Stage0MimoConfig": ("fhe_native_mamba3.benchmarks.stage0_mimo", "Stage0MimoConfig"),
    "Stage0SweepConfig": ("fhe_native_mamba3.benchmarks.stage0_sweep", "Stage0SweepConfig"),
    "StateDictMappingReport": ("fhe_native_mamba3.state_dict_mapping", "StateDictMappingReport"),
    "StateDictMappingRule": ("fhe_native_mamba3.state_dict_mapping", "StateDictMappingRule"),
    "StateDictMappingDraft": ("fhe_native_mamba3.state_dict_mapping", "StateDictMappingDraft"),
    "SrhtButterflyStage": ("fhe_native_mamba3.srht_sketch", "SrhtButterflyStage"),
    "SrhtSketchMetadata": ("fhe_native_mamba3.srht_sketch", "SrhtSketchMetadata"),
    "TrackingBackend": ("fhe_native_mamba3.backends.tracking", "TrackingBackend"),
    "WeightCalibration": ("fhe_native_mamba3.weight_encoding", "WeightCalibration"),
    "WeightBundleManifest": ("fhe_native_mamba3.weight_bundle", "WeightBundleManifest"),
    "WeightEncodingConfig": ("fhe_native_mamba3.weight_encoding", "WeightEncodingConfig"),
    "backend_capability_matrix": (
        "fhe_native_mamba3.backends.capabilities",
        "backend_capability_matrix",
    ),
    "build_rotation_inventory": (
        "fhe_native_mamba3.rotation_inventory",
        "build_rotation_inventory",
    ),
    "build_bootstrap_execution_schedule": (
        "fhe_native_mamba3.bootstrap_schedule",
        "build_bootstrap_execution_schedule",
    ),
    "build_prefix_scan_metadata": (
        "fhe_native_mamba3.ssd_prefix_scan",
        "build_prefix_scan_metadata",
    ),
    "build_mamba_source_recurrence_problem": (
        "fhe_native_mamba3.mamba_reference",
        "build_mamba_source_recurrence_problem",
    ),
    "build_mamba_source_visible_handoff_tensors": (
        "fhe_native_mamba3.mamba_reference",
        "build_mamba_source_visible_handoff_tensors",
    ),
    "calibrate_weight_values": (
        "fhe_native_mamba3.weight_encoding",
        "calibrate_weight_values",
    ),
    "causal_decay_weights": (
        "fhe_native_mamba3.ssd_prefix_scan",
        "causal_decay_weights",
    ),
    "compare_mamba_layer_reference": (
        "fhe_native_mamba3.mamba_reference",
        "compare_mamba_layer_reference",
    ),
    "compare_mamba_source_delta": (
        "fhe_native_mamba3.mamba_reference",
        "compare_mamba_source_delta",
    ),
    "build_weight_bundle_manifest": (
        "fhe_native_mamba3.weight_bundle",
        "build_weight_bundle_manifest",
    ),
    "build_weight_bundle_recurrence_problem": (
        "fhe_native_mamba3.bundle_recurrence",
        "build_weight_bundle_recurrence_problem",
    ),
    "adapt_mamba_state_dict_to_model": (
        "fhe_native_mamba3.mamba_checkpoint",
        "adapt_mamba_state_dict_to_model",
    ),
    "calibrate_weight_tensor": (
        "fhe_native_mamba3.weight_encoding",
        "calibrate_weight_tensor",
    ),
    "current_git_commit": (
        "fhe_native_mamba3.artifact_validation",
        "current_git_commit",
    ),
    "ckks_batch_size_for_slots": (
        "fhe_native_mamba3.backends.openfhe",
        "ckks_batch_size_for_slots",
    ),
    "ckks_ring_dimension_for_batch_size": (
        "fhe_native_mamba3.backends.openfhe",
        "ckks_ring_dimension_for_batch_size",
    ),
    "client_side_argmax": ("fhe_native_mamba3.decoding", "client_side_argmax"),
    "client_side_decode_scores": (
        "fhe_native_mamba3.decoding",
        "client_side_decode_scores",
    ),
    "client_side_decode_ciphertext": (
        "fhe_native_mamba3.decoding",
        "client_side_decode_ciphertext",
    ),
    "decoding_policies": ("fhe_native_mamba3.decoding", "decoding_policies"),
    "draft_mapping_rules": ("fhe_native_mamba3.state_dict_mapping", "draft_mapping_rules"),
    "estimate_block_cost": ("fhe_native_mamba3.cost", "estimate_block_cost"),
    "estimate_integrated_cost": ("fhe_native_mamba3.cost", "estimate_integrated_cost"),
    "estimate_cumulative_log_contraction": (
        "fhe_native_mamba3.profiling",
        "estimate_cumulative_log_contraction",
    ),
    "estimate_high_decay_burst_len": (
        "fhe_native_mamba3.profiling",
        "estimate_high_decay_burst_len",
    ),
    "evaluate_head_pack_candidate": (
        "fhe_native_mamba3.head_packing",
        "evaluate_head_pack_candidate",
    ),
    "estimate_recurrence_depth": (
        "fhe_native_mamba3.recurrence_depth",
        "estimate_recurrence_depth",
    ),
    "estimate_recurrence_stack_latency": (
        "fhe_native_mamba3.recurrence_latency",
        "estimate_recurrence_stack_latency",
    ),
    "build_stage0_status_report": (
        "fhe_native_mamba3.stage0_status",
        "build_stage0_status_report",
    ),
    "build_srht_sketch_metadata": (
        "fhe_native_mamba3.srht_sketch",
        "build_srht_sketch_metadata",
    ),
    "measure_openfhe_bootstrap_latency": (
        "fhe_native_mamba3.bootstrap_latency",
        "measure_openfhe_bootstrap_latency",
    ),
    "build_recurrence_bootstrap_plan": (
        "fhe_native_mamba3.recurrence_depth",
        "build_recurrence_bootstrap_plan",
    ),
    "greedy_bootstrap_schedule": (
        "fhe_native_mamba3.bootstrap_schedule",
        "greedy_bootstrap_schedule",
    ),
    "inspect_checkpoint": ("fhe_native_mamba3.checkpoint", "inspect_checkpoint"),
    "load_mapping_rules": ("fhe_native_mamba3.state_dict_mapping", "load_mapping_rules"),
    "make_demo_problem": ("fhe_native_mamba3.openfhe_backend", "make_demo_problem"),
    "map_state_dict": ("fhe_native_mamba3.state_dict_mapping", "map_state_dict"),
    "plaintext_static_recurrence": (
        "fhe_native_mamba3.openfhe_backend",
        "plaintext_static_recurrence",
    ),
    "plaintext_recurrence_trace": (
        "fhe_native_mamba3.openfhe_backend",
        "plaintext_recurrence_trace",
    ),
    "prefix_decay_products": (
        "fhe_native_mamba3.ssd_prefix_scan",
        "prefix_decay_products",
    ),
    "profile_model_batch": ("fhe_native_mamba3.profiling", "profile_model_batch"),
    "profile_recurrence_traces": (
        "fhe_native_mamba3.profiling",
        "profile_recurrence_traces",
    ),
    "range_loss": ("fhe_native_mamba3.range_finetune", "range_loss"),
    "fhe_aware_loss": ("fhe_native_mamba3.range_finetune", "fhe_aware_loss"),
    "mark_only_lora_trainable": (
        "fhe_native_mamba3.range_finetune",
        "mark_only_lora_trainable",
    ),
    "lora_parameter_count": (
        "fhe_native_mamba3.range_finetune",
        "lora_parameter_count",
    ),
    "profile_checkpoint_source_layers": (
        "fhe_native_mamba3.checkpoint_profile",
        "profile_checkpoint_source_layers",
    ),
    "run_checkpoint_client_decode_smoke": (
        "fhe_native_mamba3.checkpoint_decode",
        "run_checkpoint_client_decode_smoke",
    ),
    "probe_official_mamba_parity": (
        "fhe_native_mamba3.official_parity",
        "probe_official_mamba_parity",
    ),
    "apply_srht_sketch": ("fhe_native_mamba3.srht_sketch", "apply_srht_sketch"),
    "plan_mamba_checkpoint": (
        "fhe_native_mamba3.mamba_checkpoint",
        "plan_mamba_checkpoint",
    ),
    "run_checkpoint_pre_recurrence_stage_gate": (
        "fhe_native_mamba3.checkpoint_pre_recurrence",
        "run_checkpoint_pre_recurrence_stage_gate",
    ),
    "run_checkpoint_pre_recurrence_chain_gate": (
        "fhe_native_mamba3.checkpoint_pre_recurrence",
        "run_checkpoint_pre_recurrence_chain_gate",
    ),
    "run_openfhe_static_recurrence": (
        "fhe_native_mamba3.openfhe_backend",
        "run_openfhe_static_recurrence",
    ),
    "run_checkpoint_recurrence_correctness_gate": (
        "fhe_native_mamba3.checkpoint_correctness",
        "run_checkpoint_recurrence_correctness_gate",
    ),
    "run_checkpoint_full_layer_ciphertext_gate": (
        "fhe_native_mamba3.checkpoint_correctness",
        "run_checkpoint_full_layer_ciphertext_gate",
    ),
    "run_checkpoint_full_layer_ciphertexts_with_backend": (
        "fhe_native_mamba3.checkpoint_correctness",
        "run_checkpoint_full_layer_ciphertexts_with_backend",
    ),
    "run_checkpoint_full_layer_ciphertext_sweep": (
        "fhe_native_mamba3.checkpoint_full_layer_sweep",
        "run_checkpoint_full_layer_ciphertext_sweep",
    ),
    "run_checkpoint_visible_projection_sweep": (
        "fhe_native_mamba3.checkpoint_visible_projection_sweep",
        "run_checkpoint_visible_projection_sweep",
    ),
    "required_full_layer_visible_rotations": (
        "fhe_native_mamba3.checkpoint_correctness",
        "required_full_layer_visible_rotations",
    ),
    "run_static_mimo_recurrence_ciphertexts_with_backend": (
        "fhe_native_mamba3.openfhe_backend",
        "run_static_mimo_recurrence_ciphertexts_with_backend",
    ),
    "run_static_mimo_recurrence_ciphertext_chain_with_backend": (
        "fhe_native_mamba3.openfhe_backend",
        "run_static_mimo_recurrence_ciphertext_chain_with_backend",
    ),
    "scale_recurrence_state": (
        "fhe_native_mamba3.openfhe_backend",
        "scale_recurrence_state",
    ),
    "scale_recurrence_state_and_output": (
        "fhe_native_mamba3.openfhe_backend",
        "scale_recurrence_state_and_output",
    ),
    "ssd_prefix_scan": ("fhe_native_mamba3.ssd_prefix_scan", "ssd_prefix_scan"),
    "ssd_prefix_scan_prefill": (
        "fhe_native_mamba3.ssd_prefix_scan",
        "ssd_prefix_scan_prefill",
    ),
    "srht_sample_indices": ("fhe_native_mamba3.srht_sketch", "srht_sample_indices"),
    "srht_sampling_mask": ("fhe_native_mamba3.srht_sketch", "srht_sampling_mask"),
    "srht_sketch_matrix": ("fhe_native_mamba3.srht_sketch", "srht_sketch_matrix"),
    "sweep_head_pack_candidates": (
        "fhe_native_mamba3.head_packing",
        "sweep_head_pack_candidates",
    ),
    "run_stage0_mimo": ("fhe_native_mamba3.benchmarks.stage0_mimo", "run_stage0_mimo"),
    "run_stage0_sweep": ("fhe_native_mamba3.benchmarks.stage0_sweep", "run_stage0_sweep"),
    "validate_artifact_file": (
        "fhe_native_mamba3.artifact_validation",
        "validate_artifact_file",
    ),
    "validate_benchmark_artifact": (
        "fhe_native_mamba3.artifact_validation",
        "validate_benchmark_artifact",
    ),
    "load_weight_bundle_model": ("fhe_native_mamba3.weight_bundle", "load_weight_bundle_model"),
    "save_weight_bundle": ("fhe_native_mamba3.weight_bundle", "save_weight_bundle"),
    "save_weight_bundle_from_checkpoint": (
        "fhe_native_mamba3.weight_bundle",
        "save_weight_bundle_from_checkpoint",
    ),
    "save_weight_bundle_from_mapped_checkpoint": (
        "fhe_native_mamba3.weight_bundle",
        "save_weight_bundle_from_mapped_checkpoint",
    ),
    "save_mapping_draft": ("fhe_native_mamba3.state_dict_mapping", "save_mapping_draft"),
    "save_mamba_checkpoint_bundle": (
        "fhe_native_mamba3.mamba_checkpoint",
        "save_mamba_checkpoint_bundle",
    ),
}

__all__ = [
    "PRE_RECURRENCE_STAGES",
    "ArtifactValidationIssue",
    "ArtifactValidationResult",
    "BackendCapability",
    "BackendStats",
    "BootstrapExecutionBlockCost",
    "BootstrapExecutionPolicy",
    "BootstrapExecutionSchedule",
    "BootstrapExecutionScheduleStep",
    "BootstrapSchedule",
    "CheckpointClientDecodeSmoke",
    "CheckpointFullLayerCiphertextGate",
    "CheckpointFullLayerCiphertextTrace",
    "CheckpointFullLayerSweepLayer",
    "CheckpointFullLayerSweepResult",
    "CheckpointInspection",
    "CheckpointPreRecurrenceChainGate",
    "CheckpointPreRecurrenceStageGate",
    "CheckpointRecurrenceCorrectnessGate",
    "CheckpointSourceProfile",
    "CheckpointSourceProfileLayer",
    "CheckpointTensorSpec",
    "CheckpointVisibleProjectionSweepResult",
    "CheckpointVisibleProjectionSweepRow",
    "CiphertextHandoffLayer",
    "CiphertextHandoffResult",
    "CiphertextLayoutContract",
    "CkksConfig",
    "CkksTrace",
    "FHEBackend",
    "FheCostEstimate",
    "FheMamba3Block",
    "FheMamba3Config",
    "FheMamba3ForCausalLM",
    "GreedyBootstrapSchedule",
    "HeadPackCandidate",
    "HeadPackSweep",
    "IntegratedCostEstimate",
    "LoRAConfig",
    "LoRALinear",
    "MambaCheckpointAdapterReport",
    "MambaCheckpointPlan",
    "MambaLayerPlan",
    "MambaLayerReferenceResult",
    "MambaSourceDeltaResult",
    "MambaSourceLayerDiagnostics",
    "MambaSourceVisibleHandoffTensors",
    "OfficialMambaParityResult",
    "OpenFheBootstrapConfig",
    "OpenFheBootstrapLatencyConfig",
    "OpenFheCkksBackend",
    "OpenFheRecurrenceCiphertextChainResult",
    "OpenFheRecurrenceCiphertextTrace",
    "OpenFheRecurrenceProblem",
    "OpenFheRecurrenceResult",
    "PackingPlan",
    "RangeLossConfig",
    "RangeLossResult",
    "RangeLossTerm",
    "RecurrenceTraceProfile",
    "SrhtButterflyStage",
    "SrhtSketchMetadata",
    "SsdPrefixScanResult",
    "Stage0MimoConfig",
    "Stage0SweepConfig",
    "StateDictMappingDraft",
    "StateDictMappingReport",
    "StateDictMappingRule",
    "TrackingBackend",
    "WeightBundleManifest",
    "WeightBundleRecurrenceProblem",
    "WeightCalibration",
    "WeightEncodingConfig",
    "__version__",
    "adapt_mamba_state_dict_to_model",
    "apply_handoff_bootstrap_schedule",
    "apply_lora_to_linear_modules",
    "apply_srht_sketch",
    "backend_capability_matrix",
    "build_bootstrap_execution_schedule",
    "build_mamba_source_recurrence_problem",
    "build_mamba_source_visible_handoff_tensors",
    "build_prefix_scan_metadata",
    "build_recurrence_bootstrap_plan",
    "build_rotation_inventory",
    "build_srht_sketch_metadata",
    "build_stage0_status_report",
    "build_weight_bundle_manifest",
    "build_weight_bundle_recurrence_problem",
    "calibrate_weight_tensor",
    "calibrate_weight_values",
    "causal_decay_weights",
    "ckks_batch_size_for_slots",
    "ckks_ring_dimension_for_batch_size",
    "client_side_argmax",
    "client_side_decode_ciphertext",
    "client_side_decode_scores",
    "compare_mamba_layer_reference",
    "compare_mamba_source_delta",
    "current_git_commit",
    "decoding_policies",
    "draft_mapping_rules",
    "estimate_block_cost",
    "estimate_cumulative_log_contraction",
    "estimate_high_decay_burst_len",
    "estimate_integrated_cost",
    "estimate_recurrence_depth",
    "estimate_recurrence_stack_latency",
    "evaluate_head_pack_candidate",
    "fhe_aware_loss",
    "greedy_bootstrap_schedule",
    "inspect_checkpoint",
    "load_mapping_rules",
    "load_weight_bundle_model",
    "lora_parameter_count",
    "make_demo_problem",
    "map_state_dict",
    "mark_only_lora_trainable",
    "measure_openfhe_bootstrap_latency",
    "plaintext_recurrence_trace",
    "plaintext_static_recurrence",
    "plan_mamba_checkpoint",
    "prefix_decay_products",
    "probe_official_mamba_parity",
    "profile_checkpoint_source_layers",
    "profile_model_batch",
    "profile_recurrence_traces",
    "range_loss",
    "required_full_layer_visible_rotations",
    "run_checkpoint_client_decode_smoke",
    "run_checkpoint_full_layer_ciphertext_gate",
    "run_checkpoint_full_layer_ciphertext_sweep",
    "run_checkpoint_full_layer_ciphertexts_with_backend",
    "run_checkpoint_pre_recurrence_chain_gate",
    "run_checkpoint_pre_recurrence_stage_gate",
    "run_checkpoint_recurrence_correctness_gate",
    "run_checkpoint_visible_projection_sweep",
    "run_openfhe_static_recurrence",
    "run_stage0_mimo",
    "run_stage0_sweep",
    "run_static_mimo_recurrence_ciphertext_chain_with_backend",
    "run_static_mimo_recurrence_ciphertexts_with_backend",
    "save_mamba_checkpoint_bundle",
    "save_mapping_draft",
    "save_weight_bundle",
    "save_weight_bundle_from_checkpoint",
    "save_weight_bundle_from_mapped_checkpoint",
    "scale_recurrence_state",
    "scale_recurrence_state_and_output",
    "srht_sample_indices",
    "srht_sampling_mask",
    "srht_sketch_matrix",
    "ssd_prefix_scan",
    "ssd_prefix_scan_prefill",
    "sweep_head_pack_candidates",
    "validate_artifact_file",
    "validate_benchmark_artifact",
]


def __getattr__(name: str) -> object:
    if name not in _LAZY_IMPORTS:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)
    module_name, attr_name = _LAZY_IMPORTS[name]
    module = __import__(module_name, fromlist=[attr_name])
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
